// Generated by CoffeeScript 1.6.3
var Router;

Router = Ember.Router.extend();

Router.map(function() {
  this.resource('world', function() {
    this.route('one');
    this.route('two');
    return this.route('three');
  });
  this.resource('me', function() {
    this.route('one');
    this.route('two');
    return this.route('three');
  });
  return this.resource('hunt', function() {
    this.route('one');
    this.route('two');
    return this.route('three');
  });
});

export default Router;
