// Generated by CoffeeScript 1.6.3
var Router;

Router = Ember.Router.extend();

Router.map(function() {
  return this.resource('inside', function() {
    this.route('world');
    this.route('me');
    return this.route('hunt');
  });
});

export default Router;
