// Generated by CoffeeScript 1.6.3
var Router;

Router = Ember.Router.extend();

Router.map(function() {
  this.route('component-test');
  return this.route('helper-test');
});

export default Router;
